services:
  - type: web
    name: c2p-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: c2p-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: c2p-redis
          property: connectionString

  - type: worker
    name: c2p-tomer        nique
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A tasks worker --loglevel=info --concurrency=1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: c2p-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: c2p-redis
          property: connectionString

  - type: redis
    name: c2p-redis         # ← keep this exact name only once
    ipAllowList: []

databases:
  - name: c2p-db
    databaseName: c2p
    user: c2p
