# This file tells Render exactly what to run
services:
  - type: web
    name: c2p-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
  - type: worker
    name: c2p-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A tasks worker --loglevel=info --concurrency=1
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: c2p-redis
  - type: redis
    name: c2p-redis
    ipAllowList: []
